FROM python:3.11

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2-binary

RUN pip install --upgrade pip
WORKDIR . /TestShop
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT ["./.docker-entrypoint.sh"]

CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]